version: "3.8"
services:
    contacts_webapp:
        build: ./webapp
        container_name: contacts_webapp
        ports:
            - 5000:5000
        depends_on:
            - contacts_service
        restart: unless-stopped
        networks:
            - contacts-network
    contacts_service:
        build: ./service
        container_name: contacts_service
        ports:
        - 4000:4000
        depends_on:
            - mongodb
        restart: unless-stopped
        networks:
        - contacts-network
    mongodb:
        image : mongo
        container_name: mongodb
        volumes:
        - /mongodata:/data/db
        expose:
            - "27017"
        ports:
        - 27017:27017
        restart: unless-stopped
        networks:
        - contacts-network
networks:
    contacts-network:

