version: "3.8"
services:
    todo_webapp:
        build: ./webapp
        image: khunny7/todo_webapp
        container_name: todo_webapp
        ports:
            - 5000:5000
        depends_on:
            - todo_service
        restart: unless-stopped
        networks:
            - todo-network
    todo_service:
        build: ./service
        image: khunny7/todo_service
        container_name: todo_service
        ports:
        - 4000:4000
        depends_on:
            - mongodb
        restart: unless-stopped
        networks:
        - todo-network
    mongodb:
        image : mongo
        container_name: mongodb
        volumes:
        - /mongodata:/data/db
        expose:
            - "27017"
        ports:
        - 27017:27017
        restart: unless-stopped
        networks:
        - todo-network
networks:
    todo-network:

