version: "3.8"
services:
    contacts:
        build: .
        container_name: contacts
        ports:
        - 4000:4000
        depends_on:
            - mongodb
        restart: unless-stopped
        networks:
        - contacts-network
    mongodb:
        image : mongo
        container_name: mongodb
        volumes:
        - /mongodata:/data/db
        expose:
            - "27017"
        ports:
        - 27017:27017
        restart: unless-stopped
        networks:
        - contacts-network
networks:
    contacts-network:

